apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: explicit-repos-delivery-envs
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - repoURL: https://github.com/hello-world-argocd-org/hello-world-delivery.git
                  repoName: hello-world-delivery
                  org: hello-world-argocd-org
#                - repoURL: https://github.com/hello-world-argocd-org/another-delivery.git
#                  repoName: another-delivery
#                  org: hello-world-argocd-org
          - git:
              repoURL: "{{ repoURL }}"
              revision: main            # or HEAD
              directories:
                - path: envs/*          # must exist in each listed repo
  template:
    metadata:
      name: "{{ repoName }}-{{path.basename}}"
      labels:
        org: "{{ org }}"
        repo: "{{ repoName }}"
        env:  "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: "{{ repoURL }}"
        targetRevision: main           # or HEAD
        path: .
        helm:
          releaseName: "{{ repoName }}-{{path.basename}}"
          valueFiles:
            - values.yaml
            - envs/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true