apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: orgs-delivery-envs
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - scmProvider:
              github:
                organization: hello-world-argocd-org
                allBranches: false
              filters:
                - repositoryMatch: '.*-delivery$'
          - git:
              repoURL: "https://github.com/{{ repository.owner }}/{{ repository.name }}.git"
              revision: main
              directories:
                - path: envs/*

  template:
    metadata:
      name: "{{ repository.name }}-{{path.basename}}"
      labels:
        org: "{{ repository.owner }}"
        repo: "{{ repository.name }}"
        env: "{{path.basename}}"
    spec:
      project: hello-world
      source:
        repoURL: "https://github.com/{{ repository.owner }}/{{ repository.name }}.git"
        targetRevision: main
        path: .
        helm:
          releaseName: "{{ repository.name }}-{{path.basename}}"
          valueFiles:
            - values.yaml
            - envs/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
