name: Argo CD ApplicationSet E2E (Kind)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      APPSET_DIR: applicationsets
      ARGO_NS: argocd
      ARGO_HELM_CHART_VERSION: "5.51.6"
      WAIT_ROLLOUT: "240s"
      WAIT_APPS: "90"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools (Helm, yq, jq)
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          sudo curl -fsSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          sudo apt-get update -y && sudo apt-get install -y jq

      - name: Create Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Install Argo CD (ApplicationSet enabled)
        run: |
          set -euo pipefail
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          kubectl create namespace "$ARGO_NS" --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install argocd argo/argo-cd \
            --namespace "$ARGO_NS" \
            --version "$ARGO_HELM_CHART_VERSION" \
            --set applicationSet.enabled=true \
            --wait
          kubectl -n "$ARGO_NS" rollout status deploy/argocd-repo-server --timeout="$WAIT_ROLLOUT" || true

      - name: Show what we are going to apply
        run: |
          for f in $APPSET_DIR/*.yaml; do
            echo "---- $f ----"
            yq e '.kind + " " + .metadata.name' "$f" || true
          done

      - name: Apply ApplicationSet manifests
        run: |
          kubectl -n "$ARGO_NS" apply -f "$APPSET_DIR/"

      - name: Sanity — repo-server can reach GitHub and list refs
        run: |
          set -euo pipefail
          POD=$(kubectl -n "$ARGO_NS" get pod -l app.kubernetes.io/name=argocd-repo-server -o jsonpath='{.items[0].metadata.name}')
          CONTAINER=$(kubectl -n "$ARGO_NS" get pod "$POD" -o jsonpath='{.spec.containers[0].name}')
          kubectl -n "$ARGO_NS" exec "$POD" -c "$CONTAINER" -- sh -c 'getent hosts github.com || nslookup github.com || true'
          kubectl -n "$ARGO_NS" exec "$POD" -c "$CONTAINER" -- git ls-remote https://github.com/hello-world-argocd-org/hello-world-delivery.git | head -n1

      - name: Wait for Applications to be generated
        run: |
          set -euo pipefail
          end=$((SECONDS + WAIT_APPS))
          ok=0
          while [ $SECONDS -lt $end ]; do
            count=$(kubectl -n "$ARGO_NS" get applications.argoproj.io -o json 2>/dev/null | jq '.items | length')
            if [ "${count:-0}" -ge 1 ]; then
              echo "Found $count Application(s)."
              ok=1; break
            fi
            kubectl -n "$ARGO_NS" logs deploy/argocd-repo-server --tail=10 2>/dev/null || true
            sleep 5
          done
          kubectl -n "$ARGO_NS" get applications.argoproj.io || true
          if [ "$ok" -ne 1 ]; then
            echo "❌ No Applications were generated in ${WAIT_APPS}s."; exit 1
          fi

      - name: (Optional) Show generated Application details
        if: always()
        run: |
          kubectl -n "$ARGO_NS" get applications.argoproj.io -o wide || true
          first=$(kubectl -n "$ARGO_NS" get applications.argoproj.io -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
          if [ -n "$first" ]; then
            echo "----- $first -----"
            kubectl -n "$ARGO_NS" get app "$first" -o yaml | sed -e 's/token:.*/token: REDACTED/' || true
